library(rpart)
library(rpart.plot) 
library(rattle)
veri<-read.csv(file="clipboard", header=TRUE, sep= ";" )
print(veri)
agac<-rpart(formula = RISK~BORC+GELIR+STATU,data=veri[,2:5], method="class")
print(agac) 
prp (agac, extra=104, faclen=0)
fancyRpartPlot(agac)
